function moji(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/ply-tv.html?file=https://etslive-2-vidio-com.akamaized.net/exp=1689246637~acl=/hls-p/ingest_206_*/*~hmac=e273b10f2fabd03cca3a56119b5f92da92f75da9dc879e8390c5a052a00c7af0/hls-p/ingest_206_480p/index.m3u8" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function indosiar(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/ply-tv.html?file=http://www.bbvplayline2a.com/video4.html?url=http://210.210.155.35/qwr9ew/s/s04/02.m3u8" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function mentari(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/ply-tv.html?file=https://habotv.github.io/live/mentari.m3u8" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function mnctv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/mnctv.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function antv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/antv.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function sctv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/ply-tv.html?file=https://habotv.github.io/live/sctp.m3u8" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function rcti(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/rcti.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function transtv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/transtv.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function trans7(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/trans7.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function gtv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/gtv.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function tvone(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/tvone.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function inews(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/inews.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function nettv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/nettv.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function rtv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/rtv.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function tvri(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/tvri.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function kompastv(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/kompastv.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function mncsp1(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/mncsp1.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function mncsp2(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/mncsp2.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function spotv1(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/spotv1.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function spotv2(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/spotv2.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function soccerch(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/soccerch.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function fightsport(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/fightsport.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function unify(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/unify.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function dazn17(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/dazn17.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function dazn18(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/dazn18.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function dazn37(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/dazn37.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function dazn38(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/dazn38.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function daznlaliga(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/daznlaliga.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function zona24(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/zona24.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function bein1(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/bein1.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function bein2(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/bein2.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function bein3(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/bein3.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function espn1(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/espn1.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function espn2(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/espn2.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function espn3(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/espn3.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function eleven1(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/eleven1.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function eleven2(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/eleven2.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function eleven3(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/eleven3.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function eleven4(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/eleven4.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function polsat1(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/polsat1.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function polsat2(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/polsat2.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function vexra(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/vexra.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function vpremium(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/vpremium.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function canalplus1(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/canalplus1.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function canalplus2(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/canalplus2.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function canalplus3(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/canalplus3.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function axn(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/axn.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function zeebioskop(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/zeebioskop.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function imc(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/hitmovie.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function celestrial-movie(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/celestrial-movie.html.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function celestial-clasic(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/celestial-clasic.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function triil(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/triil.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function tvn(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/tvn.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function tvnmovie(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/tvnmovie.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function hitmovie(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/hitmovie.htmll" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function one(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/one.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function galaxy(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/galaxy.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function galaxypremium(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/galaxypremium.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function animax(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/animax.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}

function nickjr(){document.getElementById("tv").innerHTML='<iframe src="https://live.sportsnews.id/p/nickjr.html" style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;allow-forms allow-pointer-lock allow-same-origin-allow-popups-allow-scripts allow-top-navigation;" allowfullscreen="true"></iframe>';}
